[package]
name = "rawrxd"
version = "0.1.0"
edition = "2021"

[dependencies]
aho-corasick = "1.1.3"
thiserror = "2.0.3"
time = { version = "0.3.17", features = ["serde-human-readable"] }

[dev-dependencies]
rstest = "0.23"
